A/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from rest_framework.authtoken.views import obtain_auth_token
from api.urls import router

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('', include('profiles.urls', namespace='profile')),
    path('', include('story.urls', namespace='story')),
    # path('api/', include('api.urls', namespace='api')),
    path('api/', include(router.urls)),
    path('api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    path('api-token-auth/', obtain_auth_token),
    path('ckeditor/', include('ckeditor_uploader.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

profiles/urls.py
from django.urls import path
from .views import *

app_name = 'profile'
urlpatterns = [
    path('profile/<int:pk>/', profile, name='profile'),
    path('add_profile/', add_profile, name='add_profile'),
    # path('create_profile/<int:user_id>/', create_profile, name='create_profile'),
    path('create_profile/<int:pk>/', CreateProfile.as_view(), name='create_profile'),
    path('edit_profile/<int:user_id>/', edit_profile, name='edit_profile'),
    # path('edit_profile/<int:pk>/', EditProfile.as_view(), name='edit_profile'),
]

story/urls.py
from django.urls import path
from .views import *

app_name = 'story'
urlpatterns = [
    # path('', home, name='home'),
    path('', Home.as_view(), name='home'),
    # path('all_story/', all_story, name='all_story'),
    path('all_story/', AllStory.as_view(), name='all_story'),
    path('create_story/', create_story, name='create_story'),
    # path('create_story/', CreateStory.as_view(), name='create_story'),
    # path('edit_story/<int:user_id>/<int:story_id>/', edit_story, name='edit_story'),
    path('edit_story/<int:pk>/', EditStory.as_view(), name='edit_story'),
    # path('delete_story/<int:user_id>/<int:story_id>/', delete_story, name='delete_story'),
    path('delete_story/<int:pk>/', DeleteStory.as_view(), name='delete_story'),
]

profiles/models.py
from django.contrib.auth.models import User
from django.db import models
from django.utils.timezone import now


class Profile(models.Model):
    GENDER = [
        ('male', 'Male'),
        ('female', 'Female'),
        ('other', 'Other')
    ]

    user = models.OneToOneField(User, models.CASCADE)
    avator = models.ImageField(upload_to='avator', unique=True, null=True, blank=True)
    bio = models.TextField(null=True, blank=True)
    age = models.PositiveSmallIntegerField(null=True, blank=True)
    phone = models.PositiveIntegerField(null=True, blank=True)
    gender = models.CharField(max_length=20, choices=GENDER, default='male')
    birthday = models.DateField(null=True, blank=True, default=now)

    def __str__(self):
        return self.user.username

profiles/forms.py
from django import forms

from profiles.models import Profile


class EditProfileForm(forms.ModelForm):
    email = forms.EmailField()
    username = forms.CharField()
    firstname = forms.CharField()
    lastname = forms.CharField()

    class Meta:
        model = Profile
        fields = ('phone', 'avator', 'bio', 'age', 'gender', 'birthday')


class CreateProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ('phone', 'avator', 'bio', 'age', 'gender', 'birthday')

profiles/views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.contrib.messages.views import SuccessMessageMixin
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse_lazy, reverse
from django.views.generic import UpdateView, CreateView
from story.models import Story
from .forms import EditProfileForm
from .models import Profile


@login_required
def profile(request, pk):
    user = get_object_or_404(User, id=pk)
    stories = Story.objects.filter(user=user)
    self_pro = False
    if request.user.id == user.id:
        self_pro = True
    return render(request, 'profile/profile.html', {'user': user, 'stories': stories, 'self_pro': self_pro})


def add_profile(request):
    user = User.objects.get(username=request.user)
    profile = Profile.objects.filter(user=user)
    if profile.exists():
        return redirect('profile:edit_profile', user.id)
    else:
        return redirect('profile:create_profile', user.id)


def create_profile(request, user_id):
    pass


class CreateProfile(SuccessMessageMixin, CreateView):
    template_name = 'profile/profile_create.html'
    model = Profile
    fields = ('phone', 'avator', 'bio', 'age', 'gender', 'birthday')
    success_message = 'Your profile created successfully'

    def get_queryset(self):
        qs = super().get_queryset()
        return qs.filter(user=self.request.user)

    def form_valid(self, form):
        user = User.objects.get(username=self.request.user)
        form.instance.user = user
        form.instance.id = user.id
        return super().form_valid(form)

    def get_success_url(self):
        return reverse('profile:profile', kwargs={'pk':self.object.id})


def edit_profile(request, user_id):
    if request.user.id == user_id:
        user = get_object_or_404(User, id=user_id)
        profile = get_object_or_404(Profile, id=user_id)
        if request.method == 'POST':
            form = EditProfileForm(request.POST, request.FILES, instance=profile)
            if form.is_valid():
                form.save()
                user.email = form.cleaned_data['email']
                user.username = form.cleaned_data['username']
                user.first_name = form.cleaned_data['firstname']
                user.last_name = form.cleaned_data['lastname']
                user.save()
                messages.success(request, 'Your profile edited successfully')
                return redirect('profile:profile', user_id)
        else:
            form = EditProfileForm(instance=profile,
                                   initial={'email': user.email,
                                            'username': user.username,
                                            'firstname': user.first_name,
                                            'lastname': user.last_name, })
        return render(request, 'profile/profile_edit.html', {'form': form})
    else:
        return redirect('login')


class EditProfile(UpdateView):
    pass

templates/profile/profile.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    <h2>Profile</h2>
    {% if self_pro %}
    <a href="{% url 'profile:add_profile' %}">Profile settings</a>
    {% endif %}
    <center><h3>{{ user.username|capfirst }}</h3></center>
    <center><img src="{{ user.profile.avator.url }}"  width="100px" height="100px"></center>
    {% if user.first_name and user.last_name %}
    <center><h3>{{ user.first_name|title  }} {{ user.last_name|title  }}</h3></center>
    {% endif %}
    <center><h4>{{ user.profile.bio }}</h4></center>
<hr>
{% for story in stories %}
    <div style="display:inline-block">
        <span>{{ story.title|title }}</span> | <small>{{ story.created|date }}</small>
        {% if self_pro %}
        <a href="{% url 'story:edit_story' story.id %}">Edit</a> /
        <a href="{% url 'story:delete_story' story.id %}">Delete</a>
        {% endif %}
        <br><br>
    {% if story.sound %}
        <audio style="display:block;" controls>
            <source src="{{ story.sound.url }}" type="audio/mp3">
        </audio>
        <br>
    {% else %}
        <p>Your browser does not support the audio element.</p>
    {% endif %}
    {% if story.cover %}
    <img style="display:block;" src="{{ story.cover.url }}" alt="{{ story.title }}" width="300px" height="300px">
    {% endif %}
        <p>{{ story.caption|capfirst }}</p>
    </div>
{% endfor %}
{% endblock %}

templates/profile/profile_create.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    <h2> Create Profile</h2>
<form action="" method="post" enctype="multipart/form-data">
  {% csrf_token %}
  {{ form.as_p }}
  <input type="submit" value="Create">
</form>
{% endblock %}

templates/profile/profile_edit.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    <h2> Edit Profile</h2>
    <form action="" method="post" enctype="multipart/form-data">
      {% csrf_token %}
      {{ form.as_p }}
      <input type="submit" value="Edit">
    </form>
{% endblock %}