A/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from rest_framework.authtoken.views import obtain_auth_token
from api.urls import router

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('', include('profiles.urls', namespace='profile')),
    path('', include('story.urls', namespace='story')),
    # path('api/', include('api.urls', namespace='api')),
    path('api/', include(router.urls)),
    path('api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    path('api-token-auth/', obtain_auth_token),
    path('ckeditor/', include('ckeditor_uploader.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/urls.py
from django.urls import path

from accounts import views

app_name = 'accounts'
urlpatterns = [
    # path('login/', views.user_login, name='login'),
    # path('logout/', views.user_logout, name='logout'),
    # path('register/', views.user_register, name='register'),
    path('register/', views.register, name='register'),
]

profiles/urls.py
from django.urls import path
from .views import *

app_name = 'profile'
urlpatterns = [
    path('profile/<int:pk>/', profile, name='profile'),
    path('add_profile/', add_profile, name='add_profile'),
    # path('create_profile/<int:user_id>/', create_profile, name='create_profile'),
    path('create_profile/<int:pk>/', CreateProfile.as_view(), name='create_profile'),
    path('edit_profile/<int:user_id>/', edit_profile, name='edit_profile'),
    # path('edit_profile/<int:pk>/', EditProfile.as_view(), name='edit_profile'),
]

story/urls.py
from django.urls import path
from .views import *

app_name = 'story'
urlpatterns = [
    # path('', home, name='home'),
    path('', Home.as_view(), name='home'),
    # path('all_story/', all_story, name='all_story'),
    path('all_story/', AllStory.as_view(), name='all_story'),
    path('create_story/', create_story, name='create_story'),
    # path('create_story/', CreateStory.as_view(), name='create_story'),
    # path('edit_story/<int:user_id>/<int:story_id>/', edit_story, name='edit_story'),
    path('edit_story/<int:pk>/', EditStory.as_view(), name='edit_story'),
    # path('delete_story/<int:user_id>/<int:story_id>/', delete_story, name='delete_story'),
    path('delete_story/<int:pk>/', DeleteStory.as_view(), name='delete_story'),
]

templates/inc/messages.html
{% if messages %}
<ul>
    {% for message in messages %}
    <li {% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
    {% endfor %}
</ul>
{% endif %}

templates/inc/navbar.html
<nav>
    <a href="{% url 'story:home' %}">Home</a> /
    <a href="{% url 'story:all_story' %}">Stories</a> /
    {% if request.user.is_authenticated %}
    <a href="{% url 'story:create_story' %}">Share Story</a> /
    <a href="{% url 'password_change' %}">Change Password</a> /
    <a href="{% url 'logout' %}">Logout</a> {% if request.user.id == user.id %} /
    {# <a href="{% url 'accounts:logout' %}">Logout</a> {% if request.user.id == user.id %} / #}
    <strong>You are logged in as <a href="{% url 'profile:profile' request.user.id %}">{{ user.username }}</a></strong>
    {% endif %}
    {% else %}
    <a href="{% url 'accounts:register' %}">Register</a> /
    {# <a href="{% url 'accounts:login' %}">Login</a> #}
    <a href="{% url 'login' %}">Login</a>
    {% endif %}
    <hr>
</nav>